# Generated by Django 6.0.5 on 2026-06-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiving',
            name='status',
            field=models.CharField(default='RECEIVED', max_length=20),
        ),
    ]
