# Generated by Django 6.0.5 on 2026-06-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_receiving_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiving',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
