# Generated by Django 6.0.5 on 2026-06-05 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_receiving_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiving',
            old_name='price',
            new_name='unit_price',
        ),
    ]
