# Generated by Django 6.0.5 on 2026-06-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_price_receiving_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiving',
            name='condition',
            field=models.CharField(choices=[('GOOD', 'Good'), ('DAMAGED', 'Damaged')], default='GOOD', max_length=10),
        ),
    ]
